### ISSUE TITLE
user-agents.json is empty

### ISSUE THREAD

**Issue by ponomkir42** [jnrbsn/user-agents#4]
Hi!

File: https://jnrbsn.github.io/user-agents/user-agents.json
Now is empty. Is it an error or this project closed?

**Comment by jnrbsn** [comment]
It's a bug. This project is not closed or abandoned. I'm working on a fix right now.

**Comment by jnrbsn** [comment]
For now, I've manually reverted the commit that emptied the file, and I fixed the update job so that it will never publish an empty list. That should make it so that whatever you have that depends on this should work again.

I'm not sure right now why it's not working because it works for me locally. I don't have much more time to work on it right now because I'm about to leave to do some traveling. It might be a couple of days before I have time to work on a permanent fix, but I promise I'll fix it as soon as I can.

**Comment by ponomkir42** [comment]
Thank you! Happy holidays!

**Comment by Vasniktel** [comment]
I've also looked into the issue and it seems that the website started to block certain IP ranges (GitHub actions included). The HTML page returned from the request has text explaining that the request IP was blocked and that they suggest using their API but I couldn't find the necessary functionality in there.

**Comment by HashLiver** [comment]
It looks like it hasn't been updated in a while.

**Comment by jnrbsn** [comment]
I know it's been a long time, but this is fixed now. The GitHub Action now makes sure there is an updated snapshot of the pages that need to be parsed on the [Internet Archive's Wayback Machine](https://web.archive.org/). It saves a new snapshot if the latest one is at least 7 days old, then it parses the page from the latest snapshot instead of the original website. Kind of funky, I know, but hey, it works. The user agents will now potentially be up to 7 days out-of-date, but I think that's completely reasonable for the purpose that I'm guessing most people use this.
